/* import './globals.css'*/
import { Inter } from 'next/font/google'
import  Terminal  from '@/components/Terminal'
import  Dots  from '@/components/Dots'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Terminal/>
        <Dots/>
        {children}
      </body>
    </html>
  )
}
